### ISSUE TITLE
[ISSUE] Cannot build CardIO module with CocoaPods on Xcode 12

### ISSUE THREAD

**Issue by isimpson** [verygoodsecurity/vgs-collect-ios#192]
**Describe the bug**
When including the VGSCollectSDK in an iOS build on Xcode 12 the pod will not link correctly without forcing exclude arm64 architecture for simulator builds.
The following build error occurs in our circleci build:
```
▸ Linking VGSCollectSDK
❌  ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/distiller/project/Pods/CardIOSDK/Carthage/Build/iOS/CardIO.framework/CardIO' for architecture arm64
```

**To Reproduce**
1. Include VGSCollecSDK pod 1.6.1 or 1.6.2
2. Build for iOS simulator in circleci env with Xcode 12.x

**Expected behavior**
Build completes successfully.

**Possible Solution**
Exclude arm64 for iOS simulator SDK builds in the VGSCollect SDK pod build settings.

**Comment by dmytrokhl** [comment]
Thanks @isimpson, we will check it.

**Comment by dmytrokhl** [comment]
@isimpson I did few tests, but could reproduce the issue.
Here are CircleCI config where I did tests:
- Xcode: "12.0" and "12.2.0"
- VGSCollectSDK: 1.6.1 and 1.6.2
- CocoaPods: 1.9.3
- SCAN_DEVICE: iPhone 11

Also didn't see issue when integrating SDK locally on my working machine with Xcode12.

Could you provide more details, probably some specific version of Xcode or Cocoapods.

**Comment by isimpson** [comment]
@dmytrokhl I was using pretty much the same environment you have, does your project exclude the arm64 architecture for simulator builds?

**Comment by dmytrokhl** [comment]
I use Standard Architecture - $(ARCHS_STANDARD) only. Similar as in our sample app - https://github.com/vgs-samples/very-spacy-food

**Comment by isimpson** [comment]
I wonder is it more related to VGSCollectSDK/CardIO do you have that included?

**Comment by dmytrokhl** [comment]
I did UI tests with VGSCollectSDK/CardIO included. After adding `arm64 ` to  Excluded Architectures  in test app didn't see any issue. 
I suppose the issue could be in `CardIO SDK` since it not supported and pretty old, will check it.

**Comment by isimpson** [comment]
Thanks for investigating, it only occurs when arm64 is NOT in excluded architectures.

**Comment by dmytrokhl** [comment]
Hi @isimpson, some updates here! 

We released [v1.6.3](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.6.3), where we excluded arm64 architectures in CardIO Dynamic Wrapper. 
But it seems that the issue is mostly related to **CardIO** build and **Carthage-Xcode 12** issue described [here](https://github.com/Carthage/Carthage/issues/3019). 
Since CardIO is static library and not supported for few years already, we made [CardIO Dynamic wrapper](https://github.com/verygoodsecurity/CardIOSDK-iOS) to make it possible to integrate CardIO into Swift framework via CocoaPods. This wrapper is actually using CardIO build made with Carthage(Xcode 11), and now Carthage doesn't work properly with Xcode 12.

Currently I'm checking for workarounds how to rebuild CardIO with Carthage in Xcode 12 and release a new version of CardIO Dynamic wrapper.

The other possible issue could be that CocoaPods don't have yet full support of Xcode 12. Xcode 12 support is released only in [v1.10.0-beta](https://blog.cocoapods.org/CocoaPods-1.10.0-beta/).

By the way I still couldn't reproduce your issue in CircleCI.

**Comment by dmytrokhl** [comment]
@isimpson we create a new `CardIOSDK` version, that is built in Xcode12, and add it to `VGSCollectSDK/CardIO` subspec.

The update is still in [testing branch](https://github.com/verygoodsecurity/vgs-collect-ios/tree/feature/update_cardio_sdk_version), so if you would like to test it, you should point `VGSCollectSDK` pods to that branch:
```
 pod 'VGSCollectSDK', :git => 'https://github.com/verygoodsecurity/vgs-collect-ios.git', :branch => 'feature/update_cardio_sdk_version'
 pod 'VGSCollectSDK/CardIO', :git => 'https://github.com/verygoodsecurity/vgs-collect-ios.git', :branch => 'feature/update_cardio_sdk_version'
```

Let us know it that fixed your issue.

**Comment by dmytrokhl** [comment]
This is fixed in VGSCollectSDK [v1.7.0](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.7.0).

**Comment by isimpson** [comment]
@dmytrokhl thanks we'll update soon 🙏

**Comment by isimpson** [comment]
@dmytrokhl I dont think this has fixed the issue we still see the following issue in our builds with the latest 1.7.0 sdk:
```
[10:52:24]: ▸ Processing VGSCollectSDK-Info.plist
[10:52:24]: ▸ Linking VGSCollectSDK
[10:52:24]: ▸ Linking VGSCollectSDK
[10:52:24]: ▸ ❌  ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/distiller/project/Pods/CardIOSDK/Carthage/Build/iOS/CardIO.framework/CardIO' for architecture arm64
[10:52:24]: ▸ ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dmytrokhl** [comment]
Hi @isimpson , do you see same issue when testing your [Demo App](https://github.com/verygoodsecurity/vgs-collect-ios/tree/master/demoapp) ?

I'm curious about the issue because we did tests on multiple machines here, as well as our customers also test this version and didn't see the issue. 
To investigate it deeper could you provide us specific version of Xcode and CocoaPods that you use. Also do you see any difference in `Build Setting` section between your project and our Demo App that could cause the issue? That could help us to reproduce it.

**Comment by isimpson** [comment]
At least we use:
`    platform :ios, '11.0'`
Your demo app is using iOS 10.1.
I'll also dig when I have time and see if I can find the issue.

**Comment by isimpson** [comment]
Ok I managed to reproduce this in your demoapp by updating the CardIOSSDK target iOS Deployment Target to iOS 9.0 and then running the following command to build the scheme:
`xcodebuild -workspace "demoapp.xcworkspace" -scheme "demoapp" -configuration "Debug" -sdk "iphonesimulator" clean build`

Error:
```
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/vgs-collect-ios/demoapp/Pods/CardIOSDK/Carthage/Build/iOS/CardIO.framework/CardIO' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dmytrokhl** [comment]
Thanks @isimpson . We support iOS10+, but will try to reproduce the issues.

**Comment by MikeFynes** [comment]
@dmytrokhl Hi, we are seeing this issue again when running on M1 devices, the CardIO dependency fails, is there any update on it?

**Comment by dmytrokhl** [comment]
Hi @MikeFynes , could you provide us more details with this issue:
-  VGSCollectSDK version
-  Cocoapods version
-  Xcode version
- Error logs(if possible)

Also does this issue reproduced only on M1 devices?

**Comment by DagAgren** [comment]
* We were using 1.6.3, but I updated to 1.7.6 and the issue is still present.
* Latest Cocoapods
* Latest Xcode

This is the build output showing the issue:

```Ld /Users/dag/Library/Developer/Xcode/DerivedData/WoltClient-ehprrlmkemhfagarjcghjowbksfw/Build/Products/Debug-iphonesimulator/VGSCollectSDK/VGSCollectSDK.framework/VGSCollectSDK normal (in target 'VGSCollectSDK' from project 'Pods')
    cd /Users/dag/Code/Wolt-iOS/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios11.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -L/Users/dag/Library/Developer/Xcode/DerivedData/WoltClient-ehprrlmkemhfagarjcghjowbksfw/Build/Products/Debug-iphonesimulator/VGSCollectSDK -F/Users/dag/Library/Developer/Xcode/DerivedData/WoltClient-ehprrlmkemhfagarjcghjowbksfw/Build/Products/Debug-iphonesimulator/VGSCollectSDK -F/Users/dag/Code/Wolt-iOS/Pods/CardIOSDK/Carthage/Build/iOS -filelist /Users/dag/Library/Developer/Xcode/DerivedData/WoltClient-ehprrlmkemhfagarjcghjowbksfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/VGSCollectSDK.build/Objects-normal/arm64/VGSCollectSDK.LinkFileList -install_name @rpath/VGSCollectSDK.framework/VGSCollectSDK -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/dag/Library/Developer/Xcode/DerivedData/WoltClient-ehprrlmkemhfagarjcghjowbksfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/VGSCollectSDK.build/Objects-normal/arm64/VGSCollectSDK_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/dag/Library/Developer/Xcode/DerivedData/WoltClient-ehprrlmkemhfagarjcghjowbksfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/VGSCollectSDK.build/Objects-normal/arm64/VGSCollectSDK.swiftmodule -framework CardIO -framework Foundation -Xlinker -no_adhoc_codesign -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/dag/Library/Developer/Xcode/DerivedData/WoltClient-ehprrlmkemhfagarjcghjowbksfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/VGSCollectSDK.build/Objects-normal/arm64/VGSCollectSDK_dependency_info.dat -o /Users/dag/Library/Developer/Xcode/DerivedData/WoltClient-ehprrlmkemhfagarjcghjowbksfw/Build/Products/Debug-iphonesimulator/VGSCollectSDK/VGSCollectSDK.framework/VGSCollectSDK

ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/dag/Code/Wolt-iOS/Pods/CardIOSDK/Carthage/Build/iOS/CardIO.framework/CardIO' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

To work around this, we disable arm64 for all targets by editing the Podfile and out xcodeproj, but, this prevents us from adding standalone test targets to our project, as those have to be built for the native architecture, and on an M1 Mac, this is arm64.

**Comment by DagAgren** [comment]
The secondary issue with test targets only happens on M1 machines, and not sure about the core issue with the linking error, as I am testing this on M1 right now, but we added this workaround before M1 machines existed so I assume it happens on Intel as well.

**Comment by dmytrokhl** [comment]
Thanks @DagAgren . I'm worry the issue could be with new architectures support in Card.io SDK, since it's not maintained anymore by PayPal. We will check what we can do from our side, as for now we couldn't reproduce the issue.

I also can recommend you to check the other [scan module](https://www.verygoodsecurity.com/docs/vgs-collect/ios-sdk/card-scan/bouncer) that could be integrated with VGSCollectSDK.

**Comment by DagAgren** [comment]
Switching to CardScan does indeed fix the issue, but CardScan is a paid service so this is far from an ideal solution.

I thought you were building CardIO yourselves? It needs to have a proper arm64 build to work.

**Comment by dmytrokhl** [comment]
We will schedule some time next week to test if it could be fixed with building card.io as xcframework.

Generally, we don't maintain card.io, since it’s [owned](https://github.com/card-io/card.io-iOS-source) by PayPal. We only did create a dynamic wrapper to make it possible to use in Swift SDK and descope users from PCI scope.

The long-term perspective will be to get rid of Card.io since it takes a lot of effort to main it with each Apple/Xcode/CocoaPods updates. Probably we will find some other free Card Scanning solution to replace it.

**Comment by dmytrokhl** [comment]
@DagAgren @MikeFynes @isimpson we did rebuild Card.io framework and release a new version that should allow to integrate CardIO module  with CocoaPods on Apple Silicon. Please check VGSCollectSDK [v1.7.13](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.7.13).
